### ISSUE TITLE
command 'extension.XTranslator' not found

### ISSUE THREAD

**Issue by yyyang1996** [code-device/x-translator#2]
system: Window 10
VS Code:  1.39.2 (user setup)
x-translator:  0.1.9

**Comment by dauberc** [comment]
同样的问题

**Comment by 8pig** [comment]
我也是 
有道翻译是要秘钥了?

**Comment by lo0ong** [comment]
没有匹配的字符串 是什么意思？ 用不了

**Comment by qiqingfu** [comment]
me too

**Comment by codexu** [comment]
是windows系统么？我这边mac没什么问题

**Comment by yyyang1996** [comment]
> 是windows系统么？我这边mac没什么问题

mac 下也不行
<img width="1471" alt="截屏2020-04-27 19 12 55" src="https://user-images.githubusercontent.com/34713301/80366042-2c32a580-88bb-11ea-9ae7-296dfddc223f.png">

**Comment by huachuan005** [comment]
没法用，，

**Comment by codexu** [comment]
请安装 v0.1.13 及以上版本
